(function(){
'use strict';
/* v8.7 reference-layout visual layer only. Core app logic untouched. */
function gear(id){try{return typeof gearById==='function'?gearById(id):null}catch(_){return null}}
function collection(){try{const all=Array.isArray(GEAR)?GEAR.length:0,made=Array.isArray(state?.craftedGear)?state.craftedGear.length:0;return all?`${made} / ${all} (${Math.round(made/all*100)}%)`:'0 / 0 (0%)'}catch(_){return'0 / 0 (0%)'}}
function addHeader(){const sec=document.querySelector('section[data-view="gear"] .section:nth-of-type(2)');if(!sec)return;let h=document.getElementById('g87Header');if(!h){h=document.createElement('div');h.id='g87Header';h.className='g87-header';h.innerHTML='<div class="g87-title"><b>装備</b><span>EQUIPMENT</span></div><div class="g87-motto">その一振りが、君を強くする。</div><div class="g87-collect">収集率 <b></b></div>';sec.insertBefore(h,sec.firstChild)}const b=h.querySelector('.g87-collect b');if(b)b.textContent=collection()}
function decorate(){addHeader();document.querySelectorAll('#gearGrid .gear-item[data-gear]').forEach(btn=>{const g=gear(btn.dataset.gear);if(!g)return;btn.classList.add('g87-card');btn.dataset.rarity=Math.max(1,Math.min(5,Number(g.rarity)||1));const box=btn.querySelector('.gicon');if(box)box.classList.add('g87-artbox');if(!btn.querySelector('.g87-seal')){const s=document.createElement('span');s.className='g87-seal';s.textContent=g.set==='abyss'?'☾':g.set==='astral'?'✦':g.set==='storm'?'⚡':g.set==='blaze'?'✹':g.set==='frost'?'❄':g.set==='dragon'?'◆':'✧';btn.appendChild(s)}if(!btn.querySelector('.g87-corners')){const c=document.createElement('span');c.className='g87-corners';c.innerHTML='<i></i><i></i><i></i><i></i>';btn.appendChild(c)}});const d=document.getElementById('gearDetail');if(d)d.classList.add('g87-detail')}
function observe(id){const el=document.getElementById(id);if(!el)return;new MutationObserver(()=>requestAnimationFrame(decorate)).observe(el,{childList:true,subtree:true})}
function boot(){const s=document.createElement('style');s.textContent=`
section[data-view="gear"]{background:radial-gradient(circle at 50% 0,rgba(112,67,16,.08),transparent 32%)!important}
.g87-header{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:11px;margin:4px 0 14px;padding:14px 13px;border:1px solid #7a5027;background:linear-gradient(180deg,#110c08,#070504);box-shadow:inset 0 0 0 1px rgba(255,208,120,.05),0 9px 26px rgba(0,0,0,.36);position:relative;overflow:hidden}.g87-header:before,.g87-header:after{content:'✦';position:absolute;color:#b77b35;opacity:.28;font-size:20px}.g87-header:before{left:7px;top:3px}.g87-header:after{right:7px;bottom:3px}.g87-title b{display:block;font-family:serif;font-size:29px;line-height:1;color:#f3d49e;text-shadow:0 0 12px rgba(255,193,86,.14)}.g87-title span{font-size:8px;letter-spacing:.22em;color:#b78c58}.g87-motto{font-family:serif;color:#d0a970;font-size:13px;letter-spacing:.05em;text-align:center}.g87-collect{font-size:10px;color:#caa36d;border:1px solid #765027;padding:7px 8px;background:#090605;white-space:nowrap}.g87-collect b{color:#ffd879}
#gearGrid{grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:10px!important}.g87-card{position:relative!important;min-height:232px!important;padding:8px!important;border:1px solid #80542a!important;background:linear-gradient(180deg,#0b0807,#050404)!important;box-shadow:inset 0 0 0 1px rgba(255,214,137,.045),0 8px 20px rgba(0,0,0,.42)!important;overflow:hidden!important}.g87-card:before{content:'';position:absolute;inset:5px;border:1px solid rgba(203,142,65,.20);pointer-events:none}.g87-card[data-rarity="5"]{border-color:#b77b2f!important;box-shadow:inset 0 0 0 1px rgba(255,225,145,.08),0 0 18px rgba(194,126,34,.10),0 9px 24px rgba(0,0,0,.48)!important}.g87-artbox{height:148px!important;min-height:148px!important;margin:0 0 8px!important;border:1px solid rgba(145,93,40,.66)!important;background:radial-gradient(circle at 50% 50%,rgba(98,54,35,.14),transparent 45%),#050404!important;overflow:hidden!important;display:flex!important;align-items:center!important;justify-content:center!important}.g87-artbox>svg,.g87-artbox>img{width:118%!important;height:118%!important;max-width:none!important;max-height:none!important;filter:saturate(1.12) contrast(1.05) drop-shadow(0 0 8px rgba(255,188,78,.18)) drop-shadow(0 2px 0 rgba(0,0,0,.85))!important}.g87-card>b{font-family:serif!important;font-size:14px!important;color:#efe0c4!important;position:relative;z-index:2}.g87-card .tiny-badge.rare{color:#ffd45f!important;text-shadow:0 0 7px rgba(255,197,53,.34)}.g87-card small{color:#8c7a69!important;position:relative;z-index:2}.g87-seal{position:absolute;right:14px;top:17px;font-size:25px;color:#9b6c40;opacity:.13;pointer-events:none;filter:drop-shadow(0 0 8px currentColor)}.g87-corners i{position:absolute;width:14px;height:14px;border-color:#a87532;opacity:.72;pointer-events:none;z-index:3}.g87-corners i:nth-child(1){left:5px;top:5px;border-left:2px solid;border-top:2px solid}.g87-corners i:nth-child(2){right:5px;top:5px;border-right:2px solid;border-top:2px solid}.g87-corners i:nth-child(3){left:5px;bottom:5px;border-left:2px solid;border-bottom:2px solid}.g87-corners i:nth-child(4){right:5px;bottom:5px;border-right:2px solid;border-bottom:2px solid}
#gearTabs{background:#090605!important;border:1px solid #604021!important;padding:7px!important;gap:7px!important;border-radius:3px!important}#gearTabs button{min-height:43px!important;border:1px solid #6f4929!important;background:#0c0806!important;color:#d6b48a!important}#gearTabs button.active{background:linear-gradient(180deg,#744a17,#35210d)!important;color:#fff0c9!important;box-shadow:inset 0 0 0 1px #a77734,0 0 12px rgba(207,137,48,.14)!important}
.g87-detail{background:linear-gradient(180deg,#0d0908,#050404)!important;border-color:#795027!important;box-shadow:inset 0 0 0 1px rgba(255,210,120,.04),0 0 22px rgba(0,0,0,.3)!important}.g87-detail .detail-icon{width:130px!important;height:130px!important;min-width:130px!important;background:#050404!important;border:1px solid #84592b!important;overflow:hidden!important}.g87-detail .detail-icon>svg,.g87-detail .detail-icon>img{width:118%!important;height:118%!important;max-width:none!important;max-height:none!important;filter:saturate(1.12) contrast(1.05) drop-shadow(0 0 10px rgba(255,190,85,.18))!important}
@media(max-width:420px){.g87-header{grid-template-columns:auto 1fr;gap:7px}.g87-collect{grid-column:1/-1;justify-self:end}.g87-title b{font-size:24px}.g87-motto{font-size:11px}.g87-card{min-height:220px!important}.g87-artbox{height:136px!important;min-height:136px!important}.g87-detail .detail-icon{width:112px!important;height:112px!important;min-width:112px!important}}
`;document.head.appendChild(s);decorate();observe('gearGrid');observe('gearDetail');observe('gearTabs');document.getElementById('nav')?.addEventListener('click',()=>setTimeout(decorate,0));document.getElementById('gearTabs')?.addEventListener('click',()=>setTimeout(decorate,0));document.getElementById('gearGrid')?.addEventListener('click',()=>setTimeout(decorate,0))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();