(function(){
'use strict';
function byId(id){try{return typeof gearById==='function'?gearById(id):null}catch(_){return null}}
function isP95(g){return !!(g&&String(g.id||'').startsWith('photo95_')&&Number.isInteger(g._photo95Index));}
function sprite(g,large=false){if(!isP95(g))return'';const i=g._photo95Index,c=i%5,r=Math.floor(i/5);return `<span class="weapon95-sprite${large?' large':''}" style="--c:${c};--r:${r}"></span>`;}
function installStyle(){if(document.getElementById('weapon95-style'))return;const s=document.createElement('style');s.id='weapon95-style';s.textContent=`
#gearGrid{grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:8px!important}
#gearGrid .gear-item{min-width:0!important;padding:6px!important}
.weapon95-icon,.weapon95-detail-icon{overflow:hidden;background:#eadfbd;border:1px solid #4d3921;border-radius:8px;padding:0!important}
.weapon95-icon{height:88px}.weapon95-detail-icon{height:180px;width:180px;max-width:48vw}
.weapon95-sprite{display:block;width:100%;height:100%;background-image:url('weapon95_photo20.webp?v=95');background-repeat:no-repeat;background-size:500% 400%;background-position:calc(var(--c) * 25%) calc(var(--r) * 33.333333%);image-rendering:pixelated;image-rendering:crisp-edges;filter:none!important;transform:none!important}
.weapon95-card .weapon-name{font-size:9px;line-height:1.15;margin-top:5px;display:block;white-space:normal}
.weapon95-card .gmeta{gap:2px!important}.weapon95-card .tiny-badge{font-size:8px!important;padding:2px 3px!important}
@media(min-width:700px){#gearGrid{grid-template-columns:repeat(5,minmax(0,1fr))!important}.weapon95-icon{height:112px}}
`;document.head.appendChild(s)}
function renderGrid(){const area=document.getElementById('gearGrid');if(!area)return;const list=(Array.isArray(GEAR)?GEAR:[]).filter(g=>g&&g.slot===gearSlot),crafted=Array.isArray(state.craftedGear)?state.craftedGear:[],eq=state.equipped||{};if(gearSlot!=='weapon'){if(typeof window.__p95Grid==='function')return window.__p95Grid();return}if(!selectedGear||!list.some(g=>g.id===selectedGear))selectedGear=eq.weapon||list[0]?.id||null;area.innerHTML='';list.forEach(g=>{const made=crafted.includes(g.id),equipped=eq.weapon===g.id,r=Math.max(1,Math.min(5,Number(g.rarity)||1));const b=document.createElement('button');b.type='button';b.dataset.gear=g.id;b.className=`gear-item weapon95-card r${r} ${selectedGear===g.id?'selected ':''}${made?'':'locked '}`;b.innerHTML=`<div class="weapon95-icon">${sprite(g)}</div><b class="weapon-name">${escapeHtml(g.name||'武器')}</b><div class="gmeta"><span class="tiny-badge rare">${'★'.repeat(r)}</span></div><small>${equipped?'装備中':made?'作成済み':'未作成'}</small>`;area.appendChild(b)});}
function renderDetail(){const area=document.getElementById('gearDetail');if(!area)return;const g=byId(selectedGear);if(!g){area.innerHTML='<div class="muted">装備を選択してください。</div>';return}if(g.slot!=='weapon'){if(typeof window.__p95Detail==='function')return window.__p95Detail();return}const crafted=Array.isArray(state.craftedGear)?state.craftedGear:[],eq=state.equipped||{},inv=state.inventory||{},costObj=g.cost||{},made=crafted.includes(g.id),equipped=eq.weapon===g.id,craftable=Object.entries(costObj).every(([m,n])=>(Number(inv[m])||0)>=(Number(n)||0)),r=Math.max(1,Math.min(5,Number(g.rarity)||1));const cost=Object.entries(costObj).map(([m,n])=>`${MATS[m]||m} ${Number(inv[m])||0}/${Number(n)||0}`).join(' ・ ')||'なし';area.innerHTML=`<div class="detail-head"><div class="weapon95-detail-icon">${sprite(g,true)}</div><div><div class="detail-name">${escapeHtml(g.name||'武器')}</div><div class="stars">${'★'.repeat(r)}${'☆'.repeat(5-r)}</div><div>攻撃倍率 ×${(Number(g.power)||1).toFixed(2)}</div></div></div><div class="costs">必要素材：${cost}</div><div class="detail-actions"><button class="btn gold" id="craftGear" ${made||!craftable?'disabled':''}>${made?'作成済み':craftable?'作成する':'素材不足'}</button><button class="btn primary" id="equipGear" ${made?'':'disabled'}>${equipped?'装備を外す':'装備する'}</button></div>`;}
function install(){installStyle();if(typeof window.renderGearGrid==='function'&&!window.__p95Grid)window.__p95Grid=window.renderGearGrid;if(typeof window.renderGearDetail==='function'&&!window.__p95Detail)window.__p95Detail=window.renderGearDetail;window.renderGearGrid=renderGrid;window.renderGearDetail=renderDetail;const old=window.renderGear;window.renderGear=function(){if(typeof old==='function')old();renderGrid();renderDetail();};try{renderGear()}catch(_){renderGrid();renderDetail()}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();