(function(){'use strict';
function isW(g){return !!(g&&String(g.id||'').startsWith('photo96_')&&Number.isInteger(g._photo96Index));}
function byId(id){try{return typeof gearById==='function'?gearById(id):null}catch(_){return null}}
function tile(g,large){if(!isW(g))return'';const i=g._photo96Index,c=i%5,r=Math.floor(i/5);return `<div class="w100box${large?' large':''}"><div class="w100sprite" style="--c:${c};--r:${r}"></div></div>`;}
function css(){if(document.getElementById('w100css'))return;const s=document.createElement('style');s.id='w100css';s.textContent=`#gearGrid{grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:8px!important}#gearGrid .gear-item{padding:6px!important;min-width:0!important;background:#0b0907!important;border:1px solid #5b4022!important}.w100box{width:100%;aspect-ratio:1/1;overflow:hidden;border-radius:8px;background:#eadfbd}.w100box.large{width:min(210px,54vw);height:min(210px,54vw);aspect-ratio:auto;flex:0 0 auto}.w100sprite{width:100%;height:100%;background-image:url('weapon95_photo20.webp?v=100');background-repeat:no-repeat;background-size:500% 400%;background-position:calc(var(--c)*25%) calc(var(--r)*33.333333%);image-rendering:auto;filter:none!important;transform:none!important}.w100card .gmeta,.w100card small{display:none!important}.w100card .weapon-name{font-size:9px;line-height:1.2;margin-top:5px;display:block;color:#ead9b6}#gearDetail .detail-head{align-items:center!important;gap:12px!important}@media(min-width:700px){#gearGrid{grid-template-columns:repeat(5,minmax(0,1fr))!important}}`;document.head.appendChild(s)}
function grid(){const a=document.getElementById('gearGrid');if(!a)return;if(typeof gearSlot==='undefined'||gearSlot!=='weapon'){if(typeof window.__w100g==='function')return window.__w100g();return}const list=(Array.isArray(GEAR)?GEAR:[]).filter(g=>g&&g.slot==='weapon'&&isW(g)),crafted=Array.isArray(state?.craftedGear)?state.craftedGear:[],eq=state?.equipped||{};if(!selectedGear||!list.some(g=>g.id===selectedGear))selectedGear=(eq.weapon&&list.some(g=>g.id===eq.weapon)?eq.weapon:null)||list[0]?.id||null;a.innerHTML='';list.forEach(g=>{const b=document.createElement('button');b.type='button';b.dataset.gear=g.id;b.className=`gear-item w100card ${selectedGear===g.id?'selected ':''}${crafted.includes(g.id)?'':'locked '}`;b.innerHTML=`${tile(g,false)}<b class="weapon-name">${escapeHtml(g.name||'武器')}</b>`;a.appendChild(b)});}
function detail(){const a=document.getElementById('gearDetail');if(!a)return;const g=byId(selectedGear);if(!g){a.innerHTML='<div class="muted">装備を選択してください。</div>';return}if(g.slot!=='weapon'||!isW(g)){if(typeof window.__w100d==='function')return window.__w100d();return}const crafted=Array.isArray(state?.craftedGear)?state.craftedGear:[],eq=state?.equipped||{},inv=state?.inventory||{},costObj=g.cost||{},made=crafted.includes(g.id),equipped=eq.weapon===g.id,craftable=Object.entries(costObj).every(([m,n])=>(Number(inv[m])||0)>=(Number(n)||0)),cost=Object.entries(costObj).map(([m,n])=>`${MATS[m]||m} ${Number(inv[m])||0}/${Number(n)||0}`).join(' ・ ')||'なし';a.innerHTML=`<div class="detail-head">${tile(g,true)}<div><div class="detail-name">${escapeHtml(g.name||'武器')}</div><div>攻撃倍率 ×${(Number(g.power)||1).toFixed(2)}</div></div></div><div class="costs">必要素材：${cost}</div><div class="detail-actions"><button class="btn gold" id="craftGear" ${made||!craftable?'disabled':''}>${made?'作成済み':craftable?'作成する':'素材不足'}</button><button class="btn primary" id="equipGear" ${made?'':'disabled'}>${equipped?'装備を外す':'装備する'}</button></div>`;}
function install(){css();if(typeof window.renderGearGrid==='function'&&!window.__w100g)window.__w100g=window.renderGearGrid;if(typeof window.renderGearDetail==='function'&&!window.__w100d)window.__w100d=window.renderGearDetail;window.renderGearGrid=grid;window.renderGearDetail=detail;const old=window.renderGear;window.renderGear=function(){if(typeof old==='function')old();grid();detail();};try{grid();detail();}catch(e){console.error(e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();