(function(){'use strict';
function byId(id){try{return typeof gearById==='function'?gearById(id):null}catch(_){return null}}
function isW(g){return !!(g&&g.slot==='weapon'&&Number.isInteger(g._photo96Index));}
function stars(n){n=Math.max(1,Math.min(5,Number(n)||1));return `<span class="w115-stars">${'★'.repeat(n)}<i>${'☆'.repeat(5-n)}</i></span>`}
function srcFor(g){return isW(g)&&Array.isArray(window.W115_IMAGES)?(window.W115_IMAGES[g._photo96Index]||''):''}
function art(g,large=false){const src=srcFor(g);return `<span class="w115-art${large?' large':''}">${src?`<img class="w115-img" src="${src}" alt="${escapeHtml(g.name||'武器')}">`:''}</span>`}
function css(){if(document.getElementById('w115-style'))return;const s=document.createElement('style');s.id='w115-style';s.textContent=`#gearGrid{grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:8px!important}#gearGrid .gear-item{padding:7px!important;background:linear-gradient(180deg,#100b08,#080604)!important;border:1px solid #5b3c1f!important;border-radius:8px!important;overflow:hidden!important}#gearGrid .gear-item::before,#gearGrid .gear-item::after{content:none!important;display:none!important}.w115-art{display:flex;align-items:center;justify-content:center;position:relative;width:100%;aspect-ratio:1/1;overflow:hidden;border-radius:7px;background:radial-gradient(circle at 50% 46%,#25180e,#090604 74%)}.w115-art.large{width:min(330px,72vw);aspect-ratio:1/1;background:radial-gradient(circle at 50% 46%,#2a1b0f,#090604 76%)}.w115-img{display:block!important;width:100%!important;height:100%!important;max-width:100%!important;max-height:100%!important;object-fit:contain!important;transform:none!important;filter:none!important;image-rendering:auto!important}.w115-name{display:block;margin-top:7px;font-size:11px;line-height:1.2;color:#f0dfb6;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.w115-stars{display:block!important;margin-top:5px!important;color:#e8a936!important;font-size:13px!important;letter-spacing:1px!important;line-height:1!important}.w115-stars i{font-style:normal;color:#4d3b27}.w115-card .stars,.w115-card .rarity,.w115-card .gmeta,.w115-card small,.w115-card .g88-stars{display:none!important}.w115-detail-art{display:flex;align-items:center;justify-content:center;flex:0 0 auto;padding:10px;border:1px solid #6a4825;border-radius:11px;background:#0b0907;box-sizing:border-box}#gearDetail .detail-head{align-items:center!important;gap:16px!important}#gearDetail .detail-name{font-size:23px!important;font-weight:900!important;color:#f2dfb4!important;margin-bottom:6px!important}#gearDetail .w115-stars{font-size:19px!important;margin:6px 0 12px!important}#gearDetail .stars,#gearDetail .rarity,#gearDetail .gmeta,#gearDetail .g88-stars{display:none!important}@media(min-width:700px){#gearGrid{grid-template-columns:repeat(5,minmax(0,1fr))!important}.w115-art.large{width:360px}}`;document.head.appendChild(s)}
function clean(root){if(!root)return;root.querySelectorAll('.g88-stars,.stars,.rarity,.gmeta').forEach(el=>{if(!el.classList.contains('w115-stars'))el.remove()});[...root.querySelectorAll('small')].forEach(el=>{if(/[★☆]/.test(el.textContent||''))el.remove()});}
function grid(){const a=document.getElementById('gearGrid');if(!a)return;const list=(Array.isArray(GEAR)?GEAR:[]).filter(g=>g&&g.slot===gearSlot),crafted=Array.isArray(state.craftedGear)?state.craftedGear:[],eq=state.equipped||{};if(gearSlot!=='weapon'){if(typeof window.__w115Grid==='function')return window.__w115Grid();return}if(!selectedGear||!list.some(g=>g.id===selectedGear))selectedGear=eq.weapon||list[0]?.id||null;a.innerHTML='';list.forEach(g=>{const b=document.createElement('button');b.type='button';b.dataset.gear=g.id;b.className=`gear-item w115-card ${selectedGear===g.id?'selected ':''}${crafted.includes(g.id)?'':'locked '}`;b.innerHTML=`${art(g)}<b class="w115-name">${escapeHtml(g.name||'武器')}</b>${stars(g.rarity)}`;a.appendChild(b)});clean(a)}
function detail(){const a=document.getElementById('gearDetail');if(!a)return;const g=byId(selectedGear);if(!g){a.innerHTML='<div class="muted">装備を選択してください。</div>';return}if(g.slot!=='weapon'){if(typeof window.__w115Detail==='function')return window.__w115Detail();return}const crafted=Array.isArray(state.craftedGear)?state.craftedGear:[],eq=state.equipped||{},inv=state.inventory||{},costObj=g.cost||{},made=crafted.includes(g.id),equipped=eq.weapon===g.id,craftable=Object.entries(costObj).every(([m,n])=>(Number(inv[m])||0)>=(Number(n)||0));const cost=Object.entries(costObj).map(([m,n])=>`${MATS[m]||m} ${Number(inv[m])||0}/${Number(n)||0}`).join(' ・ ')||'なし';a.innerHTML=`<div class="detail-head"><div class="w115-detail-art">${art(g,true)}</div><div><div class="detail-name">${escapeHtml(g.name||'武器')}</div>${stars(g.rarity)}<div>攻撃倍率 ×${(Number(g.power)||1).toFixed(2)}</div></div></div><div class="costs">必要素材：${cost}</div><div class="detail-actions"><button class="btn gold" id="craftGear" ${made||!craftable?'disabled':''}>${made?'作成済み':craftable?'作成する':'素材不足'}</button><button class="btn primary" id="equipGear" ${made?'':'disabled'}>${equipped?'装備を外す':'装備する'}</button></div>`;clean(a)}
function install(){css();if(typeof window.renderGearGrid==='function'&&!window.__w115Grid)window.__w115Grid=window.renderGearGrid;if(typeof window.renderGearDetail==='function'&&!window.__w115Detail)window.__w115Detail=window.renderGearDetail;window.renderGearGrid=grid;window.renderGearDetail=detail;const old=window.renderGear;window.renderGear=function(){if(typeof old==='function')old();grid();detail()};const obs=new MutationObserver(()=>requestAnimationFrame(()=>{clean(document.getElementById('gearGrid'));clean(document.getElementById('gearDetail'))}));['gearGrid','gearDetail'].forEach(id=>{const el=document.getElementById(id);if(el)obs.observe(el,{childList:true,subtree:true})});try{renderGear()}catch(_){grid();detail()}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();})();