(function(){'use strict';
const ATLAS='weapon110_atlas.png?v=110';
function byId(id){try{return typeof gearById==='function'?gearById(id):null}catch(_){return null}}
function isW(g){return !!(g&&String(g.id||'').startsWith('photo96_')&&Number.isInteger(g._photo96Index));}
function stars(n){n=Math.max(1,Math.min(5,Number(n)||1));return `<span class="w110-stars">${'★'.repeat(n)}<i>${'☆'.repeat(5-n)}</i></span>`}
function art(g,large=false){if(!isW(g))return'';const i=g._photo96Index,c=i%5,r=Math.floor(i/5);return `<span class="w110-art${large?' large':''}"><span class="w110-sprite" style="--c:${c};--r:${r}"></span></span>`}
function css(){if(document.getElementById('w110-style'))return;const s=document.createElement('style');s.id='w110-style';s.textContent=`
#gearGrid{grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:8px!important}
#gearGrid .gear-item{padding:7px!important;background:linear-gradient(180deg,#100b08,#080604)!important;border:1px solid #5b3c1f!important;border-radius:8px!important;overflow:hidden!important}
#gearGrid .gear-item::before,#gearGrid .gear-item::after{content:none!important;display:none!important}
.w110-art{display:block;position:relative;width:100%;aspect-ratio:1/1;overflow:hidden;border-radius:7px;background:radial-gradient(circle at 50% 46%,#25180e,#090604 74%)}
.w110-art.large{width:min(330px,72vw);aspect-ratio:1/1;background:radial-gradient(circle at 50% 46%,#2a1b0f,#090604 76%)}
.w110-sprite{display:block;position:absolute;inset:0;background-image:url('${ATLAS}');background-repeat:no-repeat;background-size:500% 400%;background-position:calc(var(--c)*25%) calc(var(--r)*33.333333%);image-rendering:auto!important;filter:drop-shadow(0 8px 10px rgba(0,0,0,.45));transform:none!important}
.w110-name{display:block;margin-top:7px;font-size:11px;line-height:1.2;color:#f0dfb6;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.w110-stars{display:block!important;margin-top:5px!important;color:#e8a936!important;font-size:13px!important;letter-spacing:1px!important;line-height:1!important}.w110-stars i{font-style:normal;color:#4d3b27}
.w110-card .stars,.w110-card .rarity,.w110-card .gmeta,.w110-card small,.w110-card .g88-stars{display:none!important}
.w110-detail-art{display:flex;align-items:center;justify-content:center;flex:0 0 auto;padding:10px;border:1px solid #6a4825;border-radius:11px;background:#0b0907;box-sizing:border-box}
#gearDetail .detail-head{align-items:center!important;gap:16px!important}#gearDetail .detail-name{font-size:23px!important;font-weight:900!important;color:#f2dfb4!important;margin-bottom:6px!important}#gearDetail .w110-stars{font-size:19px!important;margin:6px 0 12px!important}
#gearDetail .stars,#gearDetail .rarity,#gearDetail .gmeta,#gearDetail .g88-stars{display:none!important}
@media(min-width:700px){#gearGrid{grid-template-columns:repeat(5,minmax(0,1fr))!important}.w110-art.large{width:360px}}
`;document.head.appendChild(s)}
function clean(root){if(!root)return;root.querySelectorAll('.g88-stars,.stars,.rarity,.gmeta').forEach(el=>{if(!el.classList.contains('w110-stars'))el.remove()});[...root.querySelectorAll('small')].forEach(el=>{if(/[★☆]/.test(el.textContent||''))el.remove()});[...root.childNodes].forEach(n=>{if(n.nodeType===3&&/^\s*[★☆*]+\s*$/.test(n.textContent||''))n.remove()})}
function grid(){const a=document.getElementById('gearGrid');if(!a)return;const list=(Array.isArray(GEAR)?GEAR:[]).filter(g=>g&&g.slot===gearSlot),crafted=Array.isArray(state.craftedGear)?state.craftedGear:[],eq=state.equipped||{};if(gearSlot!=='weapon'){if(typeof window.__w110Grid==='function')return window.__w110Grid();return}if(!selectedGear||!list.some(g=>g.id===selectedGear))selectedGear=eq.weapon||list[0]?.id||null;a.innerHTML='';list.forEach(g=>{const b=document.createElement('button');b.type='button';b.dataset.gear=g.id;b.className=`gear-item w110-card ${selectedGear===g.id?'selected ':''}${crafted.includes(g.id)?'':'locked '}`;b.innerHTML=`${art(g)}<b class="w110-name">${escapeHtml(g.name||'武器')}</b>${stars(g.rarity)}`;a.appendChild(b)});clean(a)}
function detail(){const a=document.getElementById('gearDetail');if(!a)return;const g=byId(selectedGear);if(!g){a.innerHTML='<div class="muted">装備を選択してください。</div>';return}if(g.slot!=='weapon'){if(typeof window.__w110Detail==='function')return window.__w110Detail();return}const crafted=Array.isArray(state.craftedGear)?state.craftedGear:[],eq=state.equipped||{},inv=state.inventory||{},costObj=g.cost||{},made=crafted.includes(g.id),equipped=eq.weapon===g.id,craftable=Object.entries(costObj).every(([m,n])=>(Number(inv[m])||0)>=(Number(n)||0));const cost=Object.entries(costObj).map(([m,n])=>`${MATS[m]||m} ${Number(inv[m])||0}/${Number(n)||0}`).join(' ・ ')||'なし';a.innerHTML=`<div class="detail-head"><div class="w110-detail-art">${art(g,true)}</div><div><div class="detail-name">${escapeHtml(g.name||'武器')}</div>${stars(g.rarity)}<div>攻撃倍率 ×${(Number(g.power)||1).toFixed(2)}</div></div></div><div class="costs">必要素材：${cost}</div><div class="detail-actions"><button class="btn gold" id="craftGear" ${made||!craftable?'disabled':''}>${made?'作成済み':craftable?'作成する':'素材不足'}</button><button class="btn primary" id="equipGear" ${made?'':'disabled'}>${equipped?'装備を外す':'装備する'}</button></div>`;clean(a)}
function install(){css();if(typeof window.renderGearGrid==='function'&&!window.__w110Grid)window.__w110Grid=window.renderGearGrid;if(typeof window.renderGearDetail==='function'&&!window.__w110Detail)window.__w110Detail=window.renderGearDetail;window.renderGearGrid=grid;window.renderGearDetail=detail;const old=window.renderGear;window.renderGear=function(){if(typeof old==='function')old();grid();detail()};const obs=new MutationObserver(()=>requestAnimationFrame(()=>{clean(document.getElementById('gearGrid'));clean(document.getElementById('gearDetail'))}));['gearGrid','gearDetail'].forEach(id=>{const el=document.getElementById(id);if(el)obs.observe(el,{childList:true,subtree:true})});try{renderGear()}catch(_){grid();detail()}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();})();