(function(){'use strict';
const ATLAS='weapon95_photo20.webp?v=120';
let IMAGES=[];
function esc(s){try{return typeof escapeHtml==='function'?escapeHtml(String(s??'')):String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}catch(_){return String(s??'')}}
function byId(id){try{return typeof gearById==='function'?gearById(id):null}catch(_){return null}}
function idx(g){const n=Number(g&&g._photo96Index);return Number.isInteger(n)&&n>=0&&n<20?n:null}
function stars(n){n=Math.max(1,Math.min(5,Number(n)||1));return `<span class="w120-stars">${'★'.repeat(n)}<i>${'☆'.repeat(5-n)}</i></span>`}
function art(g,large=false){const i=idx(g),src=i==null?'':IMAGES[i];return `<div class="w120-art${large?' large':''}">${src?`<img class="w120-img" src="${src}" alt="${esc(g.name||'武器')}">`:''}</div>`}
function css(){if(document.getElementById('w120-style'))return;const s=document.createElement('style');s.id='w120-style';s.textContent=`
.view[data-view="gear"]>.section:first-child{display:none!important}
.view[data-view="gear"]>.section:nth-of-type(2){display:block!important}
#gearTabs{display:grid!important;grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:8px!important;position:sticky!important;top:0!important;z-index:40!important;background:#0a0705!important;padding:8px!important;border:1px solid #68451f!important;border-radius:12px!important}
#gearTabs button{min-height:48px!important;border:1px solid #65441f!important;background:linear-gradient(180deg,#18120c,#0d0906)!important;color:#ead4a5!important;font-weight:900!important;border-radius:9px!important;font-size:14px!important}
#gearTabs button.active{background:linear-gradient(180deg,#9a621d,#6d4012)!important;color:#fff2c2!important;box-shadow:0 0 0 1px #d8a348 inset!important}
#gearGrid{display:grid!important;grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:8px!important;padding:8px!important;border:1px solid #5b3d20!important;background:linear-gradient(180deg,#0b0806,#070503)!important;border-radius:12px!important}
#gearGrid .gear-item{min-width:0!important;padding:7px!important;background:linear-gradient(180deg,#100b08,#080604)!important;border:1px solid #5b3c1f!important;border-radius:10px!important;overflow:hidden!important;box-shadow:none!important}
#gearGrid .gear-item.selected{border-color:#e1a53e!important;box-shadow:0 0 0 1px #e1a53e inset,0 0 18px rgba(225,165,62,.18)!important}
#gearGrid .gear-item::before,#gearGrid .gear-item::after{content:none!important;display:none!important}
.w120-art{width:100%;aspect-ratio:1/1;display:flex;align-items:center;justify-content:center;overflow:hidden;border-radius:7px;background:radial-gradient(circle at 50% 48%,#18110b 0%,#0a0705 70%)}
.w120-art.large{width:min(320px,72vw);margin:0 auto;aspect-ratio:1/1;background:radial-gradient(circle at 50% 48%,#1d140d 0%,#090604 74%)}
.w120-img{display:block!important;width:92%!important;height:92%!important;object-fit:contain!important;transform:none!important;filter:drop-shadow(0 8px 10px rgba(0,0,0,.55))!important;image-rendering:auto!important}
.w120-name{display:block;margin-top:7px;color:#f0dfb6;font-size:11px;line-height:1.25;font-weight:700;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.w120-stars{display:block!important;margin-top:5px!important;color:#f0b43d!important;font-size:14px!important;letter-spacing:1px!important;line-height:1!important;white-space:nowrap!important}.w120-stars i{font-style:normal!important;color:#4c3926!important}
.w120-card .stars,.w120-card .rarity,.w120-card .gmeta,.w120-card .g88-stars,.w120-card small{display:none!important}
#gearDetail{margin-top:12px!important;background:linear-gradient(180deg,#17100a,#0c0805)!important;border:1px solid #6b4827!important;border-radius:12px!important;padding:14px!important}
#gearDetail .detail-head{display:block!important}#gearDetail .detail-name{font-size:22px!important;font-weight:900!important;color:#f4dfae!important;margin:10px 0 4px!important}#gearDetail .w120-stars{font-size:20px!important;margin:6px 0 12px!important}
#gearDetail .stars,#gearDetail .rarity,#gearDetail .gmeta,#gearDetail .g88-stars{display:none!important}
#gearDetail .costs{margin-top:14px!important;padding-top:12px!important;border-top:1px solid #6a4826!important;line-height:1.7!important}#gearDetail .detail-actions{display:grid!important;grid-template-columns:1fr!important;gap:10px!important;margin-top:14px!important}#gearDetail .btn{min-height:50px!important;font-size:17px!important;font-weight:900!important}
@media(min-width:700px){#gearTabs{grid-template-columns:repeat(7,minmax(0,1fr))!important}#gearGrid{grid-template-columns:repeat(5,minmax(0,1fr))!important}}
`;document.head.appendChild(s)}
function clean(root){if(!root)return;root.querySelectorAll('.g88-stars,.stars,.rarity,.gmeta').forEach(el=>{if(!el.classList.contains('w120-stars'))el.remove()});[...root.querySelectorAll('small')].forEach(el=>{if(/[★☆]/.test(el.textContent||''))el.remove()})}
function grid(){const a=document.getElementById('gearGrid');if(!a)return;if(typeof gearSlot==='undefined'||gearSlot!=='weapon'){if(typeof window.__w120Grid==='function')return window.__w120Grid();return}const list=(Array.isArray(GEAR)?GEAR:[]).filter(g=>g&&g.slot==='weapon'),crafted=Array.isArray(state&&state.craftedGear)?state.craftedGear:[],eq=(state&&state.equipped)||{};if(typeof selectedGear==='undefined'||!list.some(g=>g.id===selectedGear))selectedGear=eq.weapon||list[0]?.id||null;a.innerHTML='';list.forEach(g=>{const b=document.createElement('button');b.type='button';b.dataset.gear=g.id;b.className=`gear-item w120-card ${selectedGear===g.id?'selected ':''}${crafted.includes(g.id)?'':'locked '}`;b.innerHTML=`${art(g)}<b class="w120-name">${esc(g.name||'武器')}</b>${stars(g.rarity)}`;a.appendChild(b)});clean(a)}
function detail(){const a=document.getElementById('gearDetail');if(!a)return;const g=byId(typeof selectedGear==='undefined'?null:selectedGear);if(!g){a.innerHTML='<div class="muted">装備を選択してください。</div>';return}if(g.slot!=='weapon'){if(typeof window.__w120Detail==='function')return window.__w120Detail();return}const crafted=Array.isArray(state.craftedGear)?state.craftedGear:[],eq=state.equipped||{},inv=state.inventory||{},costObj=g.cost||{},made=crafted.includes(g.id),equipped=eq.weapon===g.id,craftable=Object.entries(costObj).every(([m,n])=>(Number(inv[m])||0)>=(Number(n)||0));const cost=Object.entries(costObj).map(([m,n])=>`${(typeof MATS!=='undefined'&&MATS[m])||m} ${Number(inv[m])||0}/${Number(n)||0}`).join(' ・ ')||'なし';a.innerHTML=`<div class="detail-head">${art(g,true)}<div class="detail-name">${esc(g.name||'武器')}</div>${stars(g.rarity)}<div>攻撃倍率 ×${(Number(g.power)||1).toFixed(2)}</div></div><div class="costs">必要素材：${cost}</div><div class="detail-actions"><button class="btn gold" id="craftGear" ${made||!craftable?'disabled':''}>${made?'作成済み':craftable?'作成する':'素材不足'}</button><button class="btn primary" id="equipGear" ${made?'':'disabled'}>${equipped?'装備を外す':'装備する'}</button></div>`;clean(a)}
function processCell(src,sw,sh,ctx){const d=ctx.getImageData(0,0,sw,sh),p=d.data;let br=245,bg=230,bb=195;const c0=(5*sw+5)*4;br=p[c0]||br;bg=p[c0+1]||bg;bb=p[c0+2]||bb;const mask=new Uint8Array(sw*sh);for(let i=0,j=0;i<p.length;i+=4,j++){const dr=p[i]-br,dg=p[i+1]-bg,db=p[i+2]-bb,dist=Math.sqrt(dr*dr+dg*dg+db*db);if(dist<82&&p[i]>125&&p[i+1]>110){p[i+3]=0}else{mask[j]=1}}const seen=new Uint8Array(sw*sh),keep=new Uint8Array(sw*sh),q=new Int32Array(sw*sh);for(let s=0;s<mask.length;s++){if(!mask[s]||seen[s])continue;let h=0,t=0;q[t++]=s;seen[s]=1;const pts=[];let minx=sw,miny=sh,maxx=0,maxy=0;while(h<t){const u=q[h++],y=(u/sw)|0,x=u-y*sw;pts.push(u);if(x<minx)minx=x;if(x>maxx)maxx=x;if(y<miny)miny=y;if(y>maxy)maxy=y;const nb=[u-1,u+1,u-sw,u+sw];for(const v of nb){if(v<0||v>=mask.length||seen[v]||!mask[v])continue;const vy=(v/sw)|0,vx=v-vy*sw;if(Math.abs(vx-x)+Math.abs(vy-y)!==1)continue;seen[v]=1;q[t++]=v}}const area=pts.length,w=maxx-minx+1,hg=maxy-miny+1,starLike=area<160&&w<32&&hg<32&&miny<sh*.55;if(area>=42&&!starLike)for(const u of pts)keep[u]=1}for(let j=0,i=0;j<keep.length;j++,i+=4)if(!keep[j])p[i+3]=0;ctx.putImageData(d,0,0)}
function buildImages(done){const im=new Image();im.onload=()=>{try{const cw=Math.round(im.naturalWidth/5),ch=Math.round(im.naturalHeight/4),sheet=document.createElement('canvas');sheet.width=im.naturalWidth;sheet.height=im.naturalHeight;const sctx=sheet.getContext('2d',{willReadFrequently:true});sctx.drawImage(im,0,0);IMAGES=[];for(let n=0;n<20;n++){const c=n%5,r=(n/5)|0,cell=document.createElement('canvas');cell.width=cw;cell.height=ch;const ctx=cell.getContext('2d',{willReadFrequently:true});ctx.drawImage(sheet,c*cw,r*ch,cw,ch,0,0,cw,ch);processCell(cell,cw,ch,ctx);IMAGES.push(cell.toDataURL('image/png'))}done()}catch(e){console.error(e);done()}};im.onerror=()=>done();im.src=ATLAS}
function install(){css();if(typeof window.renderGearGrid==='function'&&!window.__w120Grid)window.__w120Grid=window.renderGearGrid;if(typeof window.renderGearDetail==='function'&&!window.__w120Detail)window.__w120Detail=window.renderGearDetail;window.renderGearGrid=grid;window.renderGearDetail=detail;const old=window.renderGear;window.renderGear=function(){if(typeof old==='function')old();grid();detail()};const g=document.getElementById('gearGrid');if(g)g.addEventListener('click',e=>{const b=e.target.closest('[data-gear]');if(!b)return;selectedGear=b.dataset.gear;grid();detail()});const obs=new MutationObserver(()=>requestAnimationFrame(()=>{clean(document.getElementById('gearGrid'));clean(document.getElementById('gearDetail'))}));['gearGrid','gearDetail'].forEach(id=>{const el=document.getElementById(id);if(el)obs.observe(el,{childList:true,subtree:true})});buildImages(()=>{try{renderGear()}catch(_){grid();detail()}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();})();