(function(){'use strict';
function byId(id){try{return typeof gearById==='function'?gearById(id):null}catch(_){return null}}
function isW(g){return !!(g&&String(g.id||'').startsWith('photo96_')&&Number.isInteger(g._photo96Index));}
function stars(n){n=Math.max(1,Math.min(5,Number(n)||1));return `<span class="w103-stars">${'★'.repeat(n)}<i>${'☆'.repeat(5-n)}</i></span>`}
function art(g,large){if(!isW(g))return'';const i=g._photo96Index,c=i%5,r=Math.floor(i/5);return `<span class="w103-crop${large?' large':''}"><span class="w103-sprite" style="--c:${c};--r:${r}"></span></span>`}
function css(){if(document.getElementById('w103-style'))return;const s=document.createElement('style');s.id='w103-style';s.textContent=`
#gearGrid{grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:8px!important}
#gearGrid .gear-item{padding:7px!important;background:#0b0907!important;border:1px solid #5a3d21!important;border-radius:8px!important;overflow:hidden!important}
.w103-crop{display:block;position:relative;width:100%;aspect-ratio:1/.74;overflow:hidden;border-radius:7px;background:#efe5c5}
.w103-sprite{display:block;position:absolute;left:0;top:0;width:100%;aspect-ratio:1/1;background-image:url('weapon97_cards.webp?v=97');background-repeat:no-repeat;background-size:500% 400%;background-position:calc(var(--c)*25%) calc(var(--r)*33.333333%);image-rendering:auto!important;filter:none!important;transform:none!important}
.w103-crop.large{width:min(180px,48vw);aspect-ratio:1/.74}.w103-crop.large .w103-sprite{width:100%}
.w103-name{display:block;margin-top:6px;font-size:10px;line-height:1.2;color:#f0dfb6;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.w103-stars{display:block;margin-top:3px;color:#e8aa35;font-size:11px;letter-spacing:1px}.w103-stars i{font-style:normal;color:#5a4932}
.w103-detail-art{display:flex;align-items:center;justify-content:center;flex:0 0 auto;padding:10px;border:1px solid #604121;border-radius:10px;background:#0b0907}
#gearDetail .detail-head{align-items:center!important;gap:14px!important}
#gearDetail .detail-name{font-size:22px!important;font-weight:900!important;color:#f2dfb4!important;margin-bottom:6px!important}
#gearDetail .w103-stars{font-size:18px;margin:5px 0 10px}
@media(min-width:700px){#gearGrid{grid-template-columns:repeat(5,minmax(0,1fr))!important}.w103-crop.large{width:190px}}
`;document.head.appendChild(s)}
function grid(){const a=document.getElementById('gearGrid');if(!a)return;const list=(Array.isArray(GEAR)?GEAR:[]).filter(g=>g&&g.slot===gearSlot),crafted=Array.isArray(state.craftedGear)?state.craftedGear:[],eq=state.equipped||{};if(gearSlot!=='weapon'){if(typeof window.__w103Grid==='function')return window.__w103Grid();return}if(!selectedGear||!list.some(g=>g.id===selectedGear))selectedGear=eq.weapon||list[0]?.id||null;a.innerHTML='';list.forEach(g=>{const b=document.createElement('button');b.type='button';b.dataset.gear=g.id;b.className=`gear-item ${selectedGear===g.id?'selected ':''}${crafted.includes(g.id)?'':'locked '}`;b.innerHTML=`${art(g,false)}<b class="w103-name">${escapeHtml(g.name||'武器')}</b>${stars(g.rarity)}`;a.appendChild(b)});}
function detail(){const a=document.getElementById('gearDetail');if(!a)return;const g=byId(selectedGear);if(!g){a.innerHTML='<div class="muted">装備を選択してください。</div>';return}if(g.slot!=='weapon'){if(typeof window.__w103Detail==='function')return window.__w103Detail();return}const crafted=Array.isArray(state.craftedGear)?state.craftedGear:[],eq=state.equipped||{},inv=state.inventory||{},costObj=g.cost||{},made=crafted.includes(g.id),equipped=eq.weapon===g.id,craftable=Object.entries(costObj).every(([m,n])=>(Number(inv[m])||0)>=(Number(n)||0));const cost=Object.entries(costObj).map(([m,n])=>`${MATS[m]||m} ${Number(inv[m])||0}/${Number(n)||0}`).join(' ・ ')||'なし';a.innerHTML=`<div class="detail-head"><div class="w103-detail-art">${art(g,true)}</div><div><div class="detail-name">${escapeHtml(g.name||'武器')}</div>${stars(g.rarity)}<div>攻撃倍率 ×${(Number(g.power)||1).toFixed(2)}</div></div></div><div class="costs">必要素材：${cost}</div><div class="detail-actions"><button class="btn gold" id="craftGear" ${made||!craftable?'disabled':''}>${made?'作成済み':craftable?'作成する':'素材不足'}</button><button class="btn primary" id="equipGear" ${made?'':'disabled'}>${equipped?'装備を外す':'装備する'}</button></div>`}
function install(){css();if(typeof window.renderGearGrid==='function'&&!window.__w103Grid)window.__w103Grid=window.renderGearGrid;if(typeof window.renderGearDetail==='function'&&!window.__w103Detail)window.__w103Detail=window.renderGearDetail;window.renderGearGrid=grid;window.renderGearDetail=detail;const old=window.renderGear;window.renderGear=function(){if(typeof old==='function')old();grid();detail()};try{renderGear()}catch(_){grid();detail()}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();})();